[package]
name = "spyware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chrono = "0.4"
dotenv = "0.15"
log = "0.4"
log4rs = "1"
once_cell = "1"
serenity = "0.11"
simple_logger = "4"
tokio = { version = "1", features = ["macros", "signal", "rt-multi-thread"] }